name: CI
on:
  push: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }
      - name: Install uberfx
        run: go install ./cmd/uberfx

      # Build and deploy docs
      - name: Install templum and build docs
        run: |
          go install github.com/cugu/templum/cmd/templum@latest
          templum --content content --output public --url "https://docs.fx.uber.space/"
        working-directory: docs
      # - name: Install uberfx-server
      #   run: uberfx install --address "tucana.uberspace.de:22" --username fx --password ${{ secrets.UBERFX_PASSWORD }}
      - name: Deploy docs to uber.space
        run: uberfx deploy
        working-directory: docs
        env:
          UBERFX_VAR_password: ${{ secrets.UBERFX_PASSWORD }}
