name: CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: { version: latest }

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: { go-version: '1.21' }

      - name: Fmt
        run: |
          make fmt

      - name: Check
        run: |
          git diff --exit-code